export const cityData = [
    {
        city: "london",
        cityRu: "Лондон",
        timezoneOffset: 0,
        temperature: "7",
        feelsLike: "-1",
        weatherId: 1,
        status: "clear_sky",
        statusRu: "Ясно",
    },
    {
        city: "paris",
        cityRu: "Париж",
        timezoneOffset: 1,
        temperature: "9",
        feelsLike: "7",
        weatherId: 2,
        status: "few_clouds",
        statusRu: "Облачно с прояснениями",
    },
    {
        city: "berlin",
        cityRu: "Берлин",
        timezoneOffset: 1,
        temperature: "5",
        feelsLike: "2",
        weatherId: 3,
        status: "scattered_clouds",
        statusRu: "Переменная облачность",
    },
    {
        city: "rome",
        cityRu: "Рим",
        timezoneOffset: 1,
        temperature: "12",
        feelsLike: "10",
        weatherId: 4,
        status: "cloudy",
        statusRu: "Облачно",
    },
    {
        city: "moscow",
        cityRu: "Москва",
        timezoneOffset: 3,
        temperature: "7",
        feelsLike: "-3",
        weatherId: 5,
        status: "shower_rain",
        statusRu: "Ливень",
    },
    {
        city: "new-york",
        cityRu: "Нью-Йорк",
        timezoneOffset: -5,
        temperature: "3",
        feelsLike: "-4",
        weatherId: 6,
        status: "rain",
        statusRu: "Дождь",
    },
    {
        city: "tokyo",
        cityRu: "Токио",
        timezoneOffset: 9,
        temperature: "15",
        feelsLike: "13",
        weatherId: 7,
        status: "thunderstorm",
        statusRu: "Гроза",
    },
    {
        city: "toronto",
        cityRu: "Торонто",
        timezoneOffset: -5,
        temperature: "1",
        feelsLike: "-5",
        weatherId: 8,
        status: "snow",
        statusRu: "Снег",
    },
    {
        city: "dubai",
        cityRu: "Дубай",
        timezoneOffset: 4,
        temperature: "25",
        feelsLike: "26",
        weatherId: 9,
        status: "mist",
        statusRu: "Туман",
    },
]
